import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Baloo_2, Roboto } from 'next/font/google'
import { CartProvider } from './context/CartContext'
import './globals.css'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  variable: '--font-roboto',
})
const baloo2 = Baloo_2({
  subsets: ['latin'],
  weight: ['700', '800'],
  variable: '--font-baloo2',
})

export const metadata: Metadata = {
  title: 'Coffee Delivery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className={`${roboto.className} ${baloo2.variable}`}>
      <body className="bg-background">
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  )
}
